### ISSUE TITLE
Add checks for instance and database ID length & characters allowed

### ISSUE THREAD

**Issue by zoercai** [googleapis/python-spanner#430]
**Is your feature request related to a problem? Please describe.**
While running tests for the sample snippets I was adding, the tests kept failing with ["invalid bah request"](https://source.cloud.google.com/results/invocations/8420cfda-45de-4a15-8a8c-5d295148d20c/targets/github%2Fpython-spanner%2Fsamples%2Fsamples/tests;group=samples.samples.snippets_test;test=test_get_instance_config;row=1) errors (e.g. "Invalid CreateInstance request." and "Invalid GetInstanceConfig request.") with no details on what made the request invalid. It turned out the instance ID (which was also being used as the instance name) was longer than the allowed limit. It would be nice to have more helpful error messages.

 **Describe the solution you'd like**
Add length and invalid character checks to the Python client library for instance and database IDs.

 **Describe alternatives you've considered**
N/A. Alternative would be to get the backend to return a more helpful message, but that's harder to do.

**Comment by harshachinta** [comment]
1. Yes, there are limits on the length of Database ID and instance ID as mentioned in https://cloud.google.com/spanner/quotas#database-limits
2. Python spanner client library should not add these checks since any changes in the constraints on the backend will need a rework on client library. Also, the failure message from the RPC indicates the reason for failure as shown below
```
google.api_core.exceptions.InvalidArgument: 400 Invalid database name: `test-feb179387423809382u9048329084329843298`. Database name must start with a lowercase letter, be 2-30 characters long, contain only lowercase letters, numbers, underscores or hyphens, and not end with an underscore or hyphen.

```
Sample code used for testing
```
# Imports the Google Cloud Client Library.
import time

from google.cloud import spanner

project_id = "span-cloud-testing"
instance_id = "harsha-test-gcloud"
database_id = "test-feb179387423809382u9048329084329843298"

spanner_client = spanner.Client(project=project_id)
instance = spanner_client.instance(instance_id)
database = instance.database(
    database_id,
    ddl_statements=[
        """CREATE TABLE Singers (
        SingerId     INT64 NOT NULL,
        FirstName    STRING(1024),
        LastName     STRING(1024),
        SingerInfo   BYTES(MAX),
        FullName   STRING(2048) AS (
            ARRAY_TO_STRING([FirstName, LastName], " ")
        ) STORED
    ) PRIMARY KEY (SingerId)""",
        """CREATE TABLE Albums (
        SingerId     INT64 NOT NULL,
        AlbumId      INT64 NOT NULL,
        AlbumTitle   STRING(MAX)
    ) PRIMARY KEY (SingerId, AlbumId),
    INTERLEAVE IN PARENT Singers ON DELETE CASCADE""",
    ],
)

operation = database.create()

print("Waiting for operation to complete...")
operation.result(300)

print("Created database {} on instance {}".format(database_id, instance_id))

```
3. Also verified snippets test behaviour,
Command : `nox -s py-3.11 -- -k  test_create_database_explicit`
Output: ![image](https://github.com/googleapis/python-spanner/assets/57220027/3f9b41be-8ad7-4a85-9db3-8d35affca160)


Closing the issue as it does not occur now.
