### ISSUE TITLE
render bug in python API documentation

### ISSUE THREAD

**Issue by mmmarklu** [googleapis/python-spanner#47]
https://googleapis.dev/python/spanner/latest/transaction-api.html  

The Parameters column is only 1 character wide

![screenshot](https://i.ibb.co/bv6x1Sm/Screen-Shot-2020-03-30-at-5-17-16-PM.png)

**Comment by HemangChothani** [comment]
It render perfectly with the `Firefox` browser, but has issue with `Chrome` browser. I think chrome didn't put line breaker appropriately, it happens due to more characters in a line.

Reason for Parameters column 1 char is :

- google.cloud.spanner_v1.proto.ExecuteSqlRequest.QueryMode.

- google.cloud.spanner_v1.proto.ExecuteSqlRequest.QueryOptions.

- Long URl.

For that we have to change few things like put a manual line breaker 

/cc @larkee  Could you suggest anything here?

**Comment by larkee** [comment]
Hey, thanks for filing this issue!

I had a look and it seems to also render incorrectly with the `Firefox` browser on my end. 

While I definitely would like to shorten the class names, I am worried that without the full path it may be more difficult for users to find the particular class. However if there were a way to link to the relevant information of that type, I think that would be an ideal outcome. Similarly, shortening the URI rather than line breaking it. 

These pages are generated from the handwritten docstrings using Sphinx. I'm not super familiar with it but from a brief look I believe there is support for doing this.

As a note, this is not the only page affected by this problem ([see here](https://googleapis.dev/python/spanner/latest/gapic/v1/api.html)) so this is likely a large scale clean up.
